#include "DFGameModeBase.h"

#include "Characters/DFEnemyBase.h"
#include "Characters/DFHeroCharacter.h"
#include "Controllers/DFHeroController.h"
#include "Blueprint/UserWidget.h"
#include "Kismet/GameplayStatics.h"
#include "Actors/DFEnemySpawner.h"

ADFGameModeBase::ADFGameModeBase()
{
	// ì›¨ì´ë¸Œ ì‹œìŠ¤í…œ í†µí•©ìš© ìƒì„±ì
	PrimaryActorTick.bCanEverTick = false;
}

// âœ… ì•¡í„° ì‚¬ë§ ì²˜ë¦¬
void ADFGameModeBase::ActorDied(AActor* DeadActor)
{
	if (DeadActor == Hero)
	{
		Hero->HandleDeath();

		if (HeroController)
		{
			HeroController->SetPlayerEnabledState(false);
		}
		
		ShowFailWidget(); // ğŸ”¹ ì‹¤íŒ¨ ìœ„ì ¯ í‘œì‹œ
	}
	else if (ADFEnemyBase* DeadEnemy = Cast<ADFEnemyBase>(DeadActor))
	{
		DeadEnemy->HandleDeath(Hero);
	}
}

// âœ… ê²Œì„ ì‹œì‘ ì‹œ í˜¸ì¶œ
void ADFGameModeBase::BeginPlay()
{
	Super::BeginPlay();

	// ì›¨ì´ë¸Œ ì‹œì‘
	if (WaveSet && WaveSet->Waves.Num() > 0)
	{
		CurrentWaveIndex = -1;
		StartNextWave();
	}
}


// âœ… ë‹¤ìŒ ì›¨ì´ë¸Œë¡œ ì§„í–‰
void ADFGameModeBase::StartNextWave()
{
	CurrentWaveIndex++;

	// ëª¨ë“  ì›¨ì´ë¸Œë¥¼ ë‹¤ í´ë¦¬ì–´í–ˆìœ¼ë©´ ì¢…ë£Œ
	if (!WaveSet || !WaveSet->Waves.IsValidIndex(CurrentWaveIndex))
	{
		ShowSuccessWidget();
		return;
	}
	
	OnWaveInfoChanged.Broadcast(CurrentWaveIndex + 1, WaveSet->Waves.Num());
	

	Hero = Cast<ADFHeroCharacter>(UGameplayStatics::GetPlayerPawn(this, 0));
	HeroController = Cast<ADFHeroController>(UGameplayStatics::GetPlayerController(this, 0));

	if (HeroController)
	{
		HeroController->SetPlayerEnabledState(false);

		FTimerHandle PlayerEnableTimerHandle;
		FTimerDelegate PlayerEnableTimerDelegate = FTimerDelegate::CreateUObject(
			HeroController,
			&ADFHeroController::SetPlayerEnabledState,
			true
		);

		GetWorldTimerManager().SetTimer(
			PlayerEnableTimerHandle,
			PlayerEnableTimerDelegate,
			StartDelay,
			false
		);
	}
	
	const FWaveInfo& CurrentWave = WaveSet->Waves[CurrentWaveIndex];
	SetupWave(CurrentWave); // ğŸ”¥ ë°”ë¡œ ì‹¤í–‰!
}

// âœ… ì›¨ì´ë¸Œ ì„¸ë¶€ ì„¸íŒ… ë° ì‹œì‘
void ADFGameModeBase::SetupWave(FWaveInfo WaveData)
{
	// ë§µì— ë°°ì¹˜ëœ ëª¨ë“  EnemySpawner ê°€ì ¸ì˜¤ê¸°
	TArray<AActor*> Spawners;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ADFEnemySpawner::StaticClass(), Spawners);
	SpawnedBoss = nullptr;

	// ê° ìŠ¤í¬ë„ˆë§ˆë‹¤ SpawnInfosì— ë§ê²Œ ì  ìƒì„±
	for (const FWaveSpawnInfo& Info : WaveData.SpawnInfos)
	{
		for (AActor* Actor : Spawners)
		{
			if (Actor->ActorHasTag(Info.SpawnerTag))
			{
				if (ADFEnemySpawner* Spawner = Cast<ADFEnemySpawner>(Actor))
				{
					Spawner->SpawnWaveEnemies(Info.EnemyClass, Info.Count, Info.SpawnInterval, Info.SpawnDelay);
				}
			}
		}
	}

	// ğŸ”¸ ì›¨ì´ë¸Œ í´ë¦¬ì–´ ì¡°ê±´ë³„ ë¶„ê¸° ì²˜ë¦¬
	if (WaveData.ClearCondition == EWaveClearCondition::SurviveTime)
	{
		// ìƒì¡´í˜• ì›¨ì´ë¸Œ: ì¼ì • ì‹œê°„ ë²„í‹°ë©´ í´ë¦¬ì–´
		GetWorldTimerManager().SetTimer(
			SurviveTimerHandle,
			this,
			&ADFGameModeBase::OnSurviveTimeEnd,
			WaveData.SurviveTime,
			false
		);

		// âœ… ë§¤ì´ˆ ë‚¨ì€ ì‹œê°„ ë¸Œë¡œë“œìºìŠ¤íŠ¸
		GetWorldTimerManager().SetTimer(
			WaveTimerUpdateHandle,
			this,
			&ADFGameModeBase::UpdateWaveTimerTick,
			1.0f,
			true
		);
		
	}
	else if (WaveData.ClearCondition == EWaveClearCondition::KillBoss && WaveData.BossClass)
	{
		// ë³´ìŠ¤ ì›¨ì´ë¸Œ: ë³´ìŠ¤ ì†Œí™˜
		FVector BossSpawnLocation(20000.0, 5230.0, 1610.0);
		FRotator BossRotation(0, 0, 0);
		FActorSpawnParameters Params;

		SpawnedBoss = GetWorld()->SpawnActor<AActor>(WaveData.BossClass, BossSpawnLocation, BossRotation, Params);
		if (SpawnedBoss)
		{
			SpawnedBoss->OnDestroyed.AddDynamic(this, &ADFGameModeBase::OnBossDied);
		}
	}
}


// âœ… ë³´ìŠ¤ ì‚¬ë§ ì‹œ í˜¸ì¶œ
void ADFGameModeBase::OnBossDied(AActor* DeadActor)
{
	UE_LOG(LogTemp, Warning, TEXT("ğŸ‘‘ ë³´ìŠ¤ ì‚¬ë§!"));
	SpawnedBoss = nullptr;
	OnSurviveTimeEnd();
}

// âœ… ì›¨ì´ë¸Œ í´ë¦¬ì–´ ì‹œ (ìƒì¡´ ì„±ê³µ or ë³´ìŠ¤ ì²˜ì¹˜)
void ADFGameModeBase::OnSurviveTimeEnd()
{
	StopAllSpawners();
	GetWorldTimerManager().ClearTimer(SurviveTimerHandle);
	GetWorldTimerManager().ClearTimer(WaveTimerUpdateHandle);

	TArray<AActor*> Enemies;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ADFEnemyBase::StaticClass(), Enemies);

	for (AActor* Enemy : Enemies)
	{
		if (Enemy && !Enemy->IsPendingKillPending())
		{
			Enemy->Destroy();
		}
	}
	
	// ë‹¤ìŒ ì›¨ì´ë¸Œë¡œ ì´ë™
	OnWaveCleared.Broadcast();
}

// âœ… ë‚¨ì€ ìŠ¤í° íƒ€ì´ë¨¸ ì¤‘ë‹¨ (ìƒì¡´ ì›¨ì´ë¸Œ ì¢…ë£Œ ì‹œ)
void ADFGameModeBase::StopAllSpawners()
{
	TArray<AActor*> Found;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ADFEnemySpawner::StaticClass(), Found);

	for (AActor* Actor : Found)
	{
		if (ADFEnemySpawner* Spawner = Cast<ADFEnemySpawner>(Actor))
		{
			Spawner->StopSpawning();
		}
	}
}

void ADFGameModeBase::UpdateWaveTimerTick()
{
	if (!GetWorld()) return;

	float Remaining = GetWorldTimerManager().GetTimerRemaining(SurviveTimerHandle);
	if (Remaining < -1.f)
	{
		GetWorldTimerManager().ClearTimer(WaveTimerUpdateHandle);
		return;
	}

	OnWaveTimeUpdated.Broadcast(Remaining);
}

void ADFGameModeBase::ShowSuccessWidget()
{
	if (SuccessWidgetClass && !ActiveEndWidget)
	{
		ActiveEndWidget = CreateWidget<UUserWidget>(GetWorld(), SuccessWidgetClass);
		if (ActiveEndWidget)
		{
			ActiveEndWidget->AddToViewport();
			APlayerController* PC = UGameplayStatics::GetPlayerController(this, 0);
			if (PC)
			{
				PC->SetShowMouseCursor(true);
				PC->SetInputMode(FInputModeUIOnly());
			}
		}
	}
}

void ADFGameModeBase::ShowFailWidget()
{
	if (FailWidgetClass && !ActiveEndWidget)
	{
		ActiveEndWidget = CreateWidget<UUserWidget>(GetWorld(), FailWidgetClass);
		if (ActiveEndWidget)
		{
			ActiveEndWidget->AddToViewport();
			APlayerController* PC = UGameplayStatics::GetPlayerController(this, 0);
			if (PC)
			{
				PC->SetShowMouseCursor(true);
				PC->SetInputMode(FInputModeUIOnly());
			}
		}
	}
}